# Generated by Django 5.1.1 on 2024-09-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('DOING', 'In progress'), ('DONE', 'Done')], default='TODO', max_length=9)),
                ('time_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
